src/Entity/Application.php
<?php

namespace App\Entity;

use App\Repository\ApplicationRepository;
use DateTimeInterface;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: ApplicationRepository::class)]
class Application
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 128)]
    private ?string $firstname = null;

    #[ORM\Column(length: 128)]
    private ?string $lastname = null;

    #[ORM\Column(length: 255)]
    private ?string $email = null;

    #[ORM\Column(length: 255)]
    private ?string $paragon = null;

    #[ORM\Column(type: Types::DATE_MUTABLE, nullable: false)]
    private ?DateTimeInterface $birth = null;

    #[ORM\Column(length: 9)]
    private ?string $phone = null;

    #[ORM\Column(length: 255)]
    private ?string $product = null;

    #[ORM\Column]
    private ?bool $legal_a = null;

    #[ORM\Column]
    private ?bool $legal_b = null;

    #[ORM\Column]
    private ?bool $legal_c = null;

    #[ORM\Column]
    private ?bool $legal_d = null;

    #[ORM\ManyToOne(inversedBy: 'applications')]
    #[ORM\JoinColumn(nullable: false)]
    private ?Shop $shop = null;

    #[ORM\ManyToOne(inversedBy: 'applications')]
    #[ORM\JoinColumn(nullable: false)]
    private ?Category $category = null;

    #[ORM\ManyToOne(inversedBy: 'applications')]
    #[ORM\JoinColumn(nullable: false)]
    private ?Where $from_where = null;

    #[ORM\Column(length: 255)]
    private ?string $img_receipt = null;


    public function getId(): ?int
    {
        return $this->id;
    }

    public function getFirstname(): ?string
    {
        return $this->firstname;
    }

    public function setFirstname(string $firstname): static
    {
        $this->firstname = $firstname;

        return $this;
    }

    public function getLastname(): ?string
    {
        return $this->lastname;
    }

    public function setLastname(string $lastname): static
    {
        $this->lastname = $lastname;

        return $this;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): static
    {
        $this->email = $email;

        return $this;
    }

    public function getParagon(): ?string
    {
        return $this->paragon;
    }

    public function setParagon(string $paragon): static
    {
        $this->paragon = $paragon;

        return $this;
    }

    public function getBirth(): ?DateTimeInterface
    {
        return $this->birth;
    }

    public function setBirth(DateTimeInterface $birth): static
    {
        $this->birth = $birth;

        return $this;
    }

    public function getPhone(): ?string
    {
        return $this->phone;
    }

    public function setPhone(string $phone): static
    {
        $this->phone = $phone;

        return $this;
    }

    public function getProduct(): ?string
    {
        return $this->product;
    }

    public function setProduct(string $product): static
    {
        $this->product = $product;

        return $this;
    }

    public function isLegalA(): ?bool
    {
        return $this->legal_a;
    }

    public function setLegalA(bool $legal_a): static
    {
        $this->legal_a = $legal_a;

        return $this;
    }

    public function isLegalB(): ?bool
    {
        return $this->legal_b;
    }

    public function setLegalB(bool $legal_b): static
    {
        $this->legal_b = $legal_b;

        return $this;
    }

    public function isLegalC(): ?bool
    {
        return $this->legal_c;
    }

    public function setLegalC(bool $legal_c): static
    {
        $this->legal_c = $legal_c;

        return $this;
    }

    public function isLegalD(): ?bool
    {
        return $this->legal_d;
    }

    public function setLegalD(bool $legal_d): static
    {
        $this->legal_d = $legal_d;

        return $this;
    }

    public function getShop(): ?Shop
    {
        return $this->shop;
    }

    public function setShop(?Shop $shop): static
    {
        $this->shop = $shop;

        return $this;
    }

    public function getCategory(): ?Category
    {
        return $this->category;
    }

    public function setCategory(?Category $category): static
    {
        $this->category = $category;

        return $this;
    }

    public function getFromWhere(): ?Where
    {
        return $this->from_where;
    }

    public function setFromWhere(?Where $from_where): static
    {
        $this->from_where = $from_where;

        return $this;
    }

    public function getImgReceipt(): ?string
    {
        return $this->img_receipt;
    }

    public function setImgReceipt(string $img_receipt): static
    {
        $this->img_receipt = $img_receipt;

        return $this;
    }

}

src/Form/ApplicationType.php
<?php

namespace App\Form;

use App\Entity\Application;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class ApplicationType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('firstname')
            ->add('lastname')
            ->add('email')
            ->add('paragon')
            ->add('birth')
            ->add('phone')
            ->add('product')
            ->add('legal_a')
            ->add('legal_b')
            ->add('legal_c')
            ->add('legal_d')
            ->add('img_receipt')
            ->add('shop')
            ->add('category')
            ->add('from_where')
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Application::class,
        ]);
    }
}

src/Controller/ApplicationController.php
<?php

namespace App\Controller;

use App\Entity\Application;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

class ApplicationController extends AbstractController
{
    #[Route('/zgloszenie/{id}', name: 'app_application_show', methods: ['GET'])]
    public function show(Application $application): Response
    {
        return $this->render('application/show.html.twig', [
            'application' => $application,
        ]);
    }
}

src/Controller/Panel/ApplicationController.php
<?php

namespace App\Controller\Panel;

use App\Entity\Application;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\HttpFoundation\RedirectResponse;
use Symfony\Component\Routing\Annotation\Route;

class ApplicationController extends AbstractController
{
    public function __construct(
        private EntityManagerInterface $manager
    )
    {
        //
    }

    #[Route('/panel/zgloszenie', name: 'app_panel_application')]
    public function index(): Response
    {
        $items = $this->manager->getRepository(Application::class)->findAll();

        return $this->render('panel/application/index.html.twig', [
            'controller_name' => 'ApplicationController',
            'items' => $items
        ]);
    }

    #[Route('/panel/zgloszenie/{id}', name: 'app_panel_application_show', methods: ['GET'])]
    public function show(Application $application): Response
    {
        return $this->render('panel/application/show.html.twig', [
            'application' => $application,
        ]);
    }

    #[Route('/panel/zgloszenie/usun/{id}', name: 'app_panel_application_delete', methods: ['GET'])]
    public function delete(Application $application): RedirectResponse
    {
        $this->manager->remove($application);
        $this->manager->flush();

        return new RedirectResponse($this->generateUrl('app_panel_application'));
    }
}

src/Controller/Panel/DashboardController.php
<?php

namespace App\Controller\Panel;

use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

class DashboardController extends AbstractController
{
    #[Route('/panel', name: 'app_panel_dashboard')]
    public function index(): Response
    {
        return $this->render('panel/dashboard/index.html.twig', [
            'controller_name' => 'DashboardController',
        ]);
    }
}

templates/panel/application/index.html.twig
{% extends 'panel.html.twig' %}

{% block title %}Remington - Wygraj Rio - panel - Zgłoszenia{% endblock %}

{% block body %}
    <section id="flashlight">
        <div class="wrap">
            <h2>DODANE ZGŁOSZENIA</h2>

            <div class="row">
                <table>
                    <thead>
                        <tr>
                            <td>id</td>
                            <td>Imię</td>
                            <td>Nazwisko</td>
                            <td>E-mail</td>
                            <td>Operacje</td>
                        </tr>
                    </thead>
                    <tbody>
                    {% for item in items %}
                        <tr>
                            <td>{{ item.id }}</td>
                            <td>{{ item.firstname }}</td>
                            <td>{{ item.lastname }}</td>
                            <td>{{ item.email }}</td>
                            <td>
                                <a href="{{ path('app_panel_application_delete', {'id': item.id}) }}" class="remove">usuń</a>
                                <a href="{{ path('app_panel_application_show', {'id': item.id}) }}" class="show">zobacz</a>
                            </td>
                        </tr>
                    {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    </section>
{% endblock %}

templates/panel/application/show.html.twig
{% extends 'panel.html.twig' %}

{% block title %}Remington - Wygraj Rio - Panel - Zgłoszenie{% endblock %}

{% block body %}
    <section class="player" id="player">
        <div class="wrap">
            <h2>{{ application.firstname }} {{application.lastname}}</h2>

            <table>
                <tbody>
                <tr>
                    <td>Imię:</td>
                    <td>{{ application.firstname }}</td>
                </tr>
                <tr>
                    <td>Nazwisko:</td>
                    <td>{{ application.lastname }}</td>
                </tr>
                <tr>
                    <td>E-mail:</td>
                    <td>{{ application.email }}</td>
                </tr>
                <tr>
                    <td>Paragon:</td>
                    <td>{{ application.paragon }}</td>
                </tr>
                <tr>
                    <td>Produkt:</td>
                    <td>{{ application.product }}</td>
                </tr>
                <tr>
                    <td>Data urodzenia:</td>
                    <td>{{ application.birth.format('Y-m-d') }}</td>
                </tr>
                <tr>
                    <td>Sklep:</td>
                    <td>{{ application.shop.name }}</td>
                </tr>
                <tr>
                    <td>Kategoria:</td>
                    <td>{{ application.category.name }}</td>
                </tr>
                <tr>
                    <td>Skąd wiesz o akcji:</td>
                    <td>{{ application.fromWhere.name }}</td>
                </tr>
                <tr>
                    <td>Legal A:</td>
                    <td>{% if (application.legalA) %}TAK{% else %}NIE{% endif %}</td>
                </tr>
                <tr>
                    <td>Legal B:</td>
                    <td>{% if (application.legalB) %}TAK{% else %}NIE{% endif %}</td>
                </tr>
                <tr>
                    <td>Legal C:</td>
                    <td>{% if (application.legalC) %}TAK{% else %}NIE{% endif %}</td>
                </tr>
                <tr>
                    <td>Legal D:</td>
                    <td>{% if (application.legalD) %}TAK{% else %}NIE{% endif %}</td>
                </tr>
                </tbody>
            </table>

            <div class="row">
                <div class="box">
                    <div class="photo">
                        <img src="{{ asset('/uploads/' ~ application.imgReceipt) }}" alt="photo" style="display: block;"
                             class="player-photo">
                    </div>
                    <div class="clear"></div>
                </div>
            </div>

        </div>
    </section>
{% endblock %}